'use client';

import { LuFilter, LuChevronDown } from 'react-icons/lu';
import { MdCalendarToday, MdLocationOn, MdApartment, MdPerson, MdWork, MdCurrencyRupee } from 'react-icons/md';
import { FaGlobeAmericas } from 'react-icons/fa';
import { useState } from 'react';

export default function Metrics() {
  const [showFilters, setShowFilters] = useState(false);

  const metrics = [
    {
      title: 'Total No of Tenants',
      value: '12,847',
      change: '+12%',
      color: 'text-blue-600',
      bgColor: 'bg-blue-100'
    },
    {
      title: 'Total Revenue Generated by Tenants',
      value: '₹2,847,392',
      change: '+8%',
      color: 'text-green-600',
      bgColor: 'bg-green-100'
    },
    {
      title: 'Pending Revenue by Tenants',
      value: '₹284,392',
      change: '+24%',
      color: 'text-purple-600',
      bgColor: 'bg-purple-100'
    }
  ];

  return (
    <div>
      {/* Header with title and filter button */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-3xl font-semibold text-gray-700">Command Center</h2>
          <p className="text-sm text-gray-500">Complete platform visibility and control</p>
        </div>
        <button 
          className="flex items-center gap-2 px-4 py-2 bg-blue-100 text-blue-600 rounded-lg hover:bg-blue-200 transition-colors"
          onClick={() => setShowFilters(!showFilters)}
        >
          <LuFilter className="w-4 h-4" />
          <span>Filters</span>
        </button>
      </div>

      {/* Filter Section */}
      {showFilters && (
        <div className="bg-white rounded-xl shadow-sm p-6 border border-gray-200 mb-8">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
            {/* Date Range */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Date Range</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <MdCalendarToday className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>Last 7 days</option>
                  <option>Last 30 days</option>
                  <option>Last 3 months</option>
                  <option>Last year</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>

            {/* Module Focus */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Module Focus</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <LuFilter className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>All Modules</option>
                  <option>Sales</option>
                  <option>Support</option>
                  <option>Finance</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>

            {/* Location */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Location</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <MdLocationOn className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>All Locations</option>
                  <option>North</option>
                  <option>South</option>
                  <option>East</option>
                  <option>West</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>

            {/* City */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">City</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <MdLocationOn className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>All Cities</option>
                  <option>New York</option>
                  <option>Los Angeles</option>
                  <option>Chicago</option>
                  <option>Houston</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>

            {/* Country */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Country</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <FaGlobeAmericas className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>All countries</option>
                  <option>United States</option>
                  <option>Canada</option>
                  <option>United Kingdom</option>
                  <option>Australia</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>

            {/* Tenant */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Tenant</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <MdApartment className="h-5 w-5 text-gray-400" />
                </div>
                <select className="block w-full pl-10 pr-10 py-2 text-gray-700 border border-gray-300 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm appearance-none">
                  <option>All Tenants</option>
                  <option>Tenant A</option>
                  <option>Tenant B</option>
                  <option>Tenant C</option>
                  <option>Tenant D</option>
                </select>
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  <LuChevronDown className="h-5 w-5 text-gray-400" />
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {metrics.map((metric, index) => {
          // Determine icon based on metric title
          let IconComponent;
          if (metric.title.includes('Total No of Tenants')) {
            IconComponent = MdPerson;
          } else if (metric.title.includes('Total Revenue Generated')) {
            IconComponent = MdWork;
          } else {
            IconComponent = MdCurrencyRupee;
          }

          return (
            <div key={index} className="bg-white rounded-xl shadow-sm p-6 border border-gray-200">
              {/* First Row - Icon and Change */}
              <div className="flex items-center justify-between mb-3">
                <div className={`w-10 h-10 rounded-lg ${metric.bgColor} flex items-center justify-center`}>
                  <IconComponent className={`w-5 h-5 ${metric.color}`} />
                </div>
                <span className={`text-xs ${metric.bgColor} ${metric.color.replace('text-', 'text-')} px-2 py-1 rounded-full`}>{metric.change}</span>
              </div>
              
              {/* Second Row - Title */}
              <div className="mb-2">
                <h3 className="text-sm font-medium text-gray-600 text-left">{metric.title}</h3>
              </div>
              
              {/* Third Row - Value */}
              <div className="text-3xl font-bold text-gray-800 text-left">{metric.value}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
