// Premium aesthetics styles for the entire Interview Management page - Compact & Sleek
const styles = {
  container: {
    display: "flex",
    height: "calc(100vh - 70px)", // navbar height
    background: "#EFF6FF",
    overflow: "hidden",
    fontFamily: "'Inter', sans-serif",
  },
  sidebar: {
    width: "340px",
    background: "white",
    padding: "18px",
    overflowY: "auto",
    position: "sticky",
    top: "0",
    height: "calc(100vh - 70px)",
    borderRight: "1px solid #E2E8F0",
    scrollbarWidth: "none", // Firefox
    msOverflowStyle: "none", // IE/Edge
  },
  sidebarHeader: {
    marginBottom: "16px",
    paddingBottom: "4px",
  },
  sidebarTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: "4px",
    letterSpacing: "-0.02em",
  },
  sidebarSubtitle: {
    fontSize: "13px",
    color: "#64748B",
    lineHeight: "1.4",
  },
  mainContent: {
    flex: "1",
    padding: "20px",
    overflowY: "auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
  },
  interviewCard: {
    background: "white",
    border: "1px solid #E2E8F0",
    borderRadius: "12px",
    padding: "14px 16px",
    marginBottom: "12px",
    cursor: "pointer",
    transition: "all 0.15s cubic-bezier(0.4, 0, 0.2, 1)",
    position: "relative",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.01)",
  },
  interviewCardActive: {
    border: "1px solid #E2E8F0",
    boxShadow: "0 4px 12px rgba(1, 99, 214, 0.06)",
    background: "rgba(1, 99, 214, 0.01)",
  },
  jobTitle: {
    fontSize: "14px",
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: "4px",
    paddingRight: "80px", // leave space for status badge
    lineHeight: "1.3",
  },
  companyName: {
    fontSize: "13px",
    color: "#64748B",
    marginBottom: "10px",
  },
  interviewMeta: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontSize: "12px",
    color: "#475569",
  },
  metaItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  statusTag: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: "600",
    textTransform: "lowercase",
  },
  statusScheduled: {
    background: "#E0EDFF",
    color: "#0163D6",
  },
  statusRescheduled: {
    background: "#FFEED6",
    color: "#D97706",
  },
  arrowIcon: {
    position: "absolute",
    right: "16px",
    bottom: "16px",
    color: "#94A3B8",
    transition: "transform 0.15s",
  },
  rescheduleInfo: {
    marginTop: "10px",
    paddingTop: "10px",
    borderTop: "1px solid #F1F5F9",
    fontSize: "12px",
    lineHeight: "1.4",
  },
  calendarContainer: {
    width: "100%",
    maxWidth: "1150px",
    position: "relative",
  },
  calendarHeader: {
    display: "flex",
    flexDirection: "column",
    marginBottom: "16px",
    gap: "12px",
  },
  calendarTitle: {
    fontSize: "20px",
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: "-0.01em",
  },
  calendarNavigation: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  navButton: {
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    background: "white",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#475569",
    transition: "all 0.15s",
  },
  todayButton: {
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    background: "white",
    height: "32px",
    padding: "0 14px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#334155",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  viewSelector: {
    display: "flex",
    alignItems: "center",
    border: "1px solid #E2E8F0",
    borderRadius: "8px",
    overflow: "hidden",
    background: "white",
    height: "32px",
  },
  viewButton: {
    background: "transparent",
    border: "none",
    padding: "0 14px",
    height: "100%",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    color: "#475569",
    transition: "all 0.15s",
    borderRight: "1px solid #E2E8F0",
  },
  viewButtonActive: {
    background: "#0163D6",
    color: "white",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    background: "#E2E8F0",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    overflow: "hidden",
    gap: "1px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.03)",
  },
  weekdayHeader: {
    background: "#F8FAFC",
    padding: "10px 0",
    textAlign: "center",
    fontSize: "11px",
    fontWeight: "700",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  calendarDay: {
    background: "white",
    minHeight: "105px",
    padding: "8px 10px",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  dayNumber: {
    fontSize: "12px",
    fontWeight: "700",
    color: "#475569",
    marginBottom: "4px",
  },
  dayNumberOtherMonth: {
    color: "#CBD5E1",
  },
  dayNumberToday: {
    background: "#0163D6",
    color: "white",
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    fontWeight: "700",
  },
  interviewEvent: {
    background: "rgba(224, 237, 255, 0.6)",
    border: "1px solid #B2D4FF",
    borderRadius: "6px",
    padding: "6px 8px",
    marginTop: "4px",
    position: "relative",
    cursor: "pointer",
    width: "100%",
    boxSizing: "border-box",
    transition: "all 0.15s ease",
  },
  eventTime: {
    color: "#0163D6",
    fontWeight: "700",
    fontSize: "10px",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginBottom: "2px",
  },
  eventTitle: {
    color: "#0055D6",
    fontWeight: "700",
    fontSize: "11px",
    lineHeight: "1.3",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    marginBottom: "1px",
  },
  eventCompany: {
    color: "#0163D6",
    fontSize: "10px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  eventRescheduledBadge: {
    position: "absolute",
    top: "4px",
    right: "4px",
    background: "#F59E0B",
    color: "white",
    fontSize: "8px",
    fontWeight: "800",
    padding: "1px 4px",
    borderRadius: "3px",
    lineHeight: "1",
    textTransform: "capitalize",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.4)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modal: {
    width: "500px",
    maxHeight: "90vh",
    overflowY: "auto",
    background: "white",
    borderRadius: "16px",
    padding: "24px",
    position: "relative",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.15)",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
  },
  closeButton: {
    position: "absolute",
    top: "20px",
    right: "20px",
    border: "none",
    background: "none",
    cursor: "pointer",
    color: "#64748B",
    transition: "color 0.2s",
  },
  modalHeader: {
    marginBottom: "20px",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: "800",
    color: "#0F172A",
    margin: "0 0 4px 0",
    letterSpacing: "-0.01em",
  },
  modalSubtitle: {
    fontSize: "13px",
    color: "#64748B",
    margin: 0,
  },
  divider: {
    border: "none",
    borderTop: "1px solid #F1F5F9",
    margin: "16px 0",
  },
};

export default styles;
